### ISSUE TITLE
release `eb-py-flask-signup-1.1.0.zip` fails to deploy

### ISSUE THREAD

**Issue by ivanistheone** [awslabs/eb-py-flask-signup#6]
The error I get is:

```
 2014-11-05 13:18:43 UTC-0500   ERROR   Your WSGIPath refers to a file that does not exist.
```

Any suggestions about what I should update to make it work? From the Config pane I see  `WSGIPath: application.py` (which is not set anywhere in the .zip file, so I assume it's a system-wide default).

Looking at the logs, I see the contents of the .zip ultimately end up in /opt/python/current/app/ right?

```
 [:error]Target WSGI script not found or unable to stat: /opt/python/current/app/application.py
```

From this I'm guessing this setting in `.ebextensions/setup.config` is not right:

```
   "aws:elasticbeanstalk:application:environment":
      "APP_CONFIG": "/var/app/app.config"
```

In general, I think it might be a good idea to generate a new release .zip file for people to play with. EB seems like awesome technology!

**Comment by jbjanvier** [comment]
+1  The best tutorial I've found about running tasks. Quite frustrating to not be able to deploy it.

**Comment by JElchison** [comment]
FYI, I received the same `WSGIPath` error when my zip file had an extra directory at the root.  (This can be caused by downloading from a GitHub branch instead of a sanctioned release.)

Ensure that application.py exists at the root of the zip that you upload.

**Comment by haotianw465** [comment]
The system default WSGI path is "application.py" as @ivanistheone  pointed out. And the correct fix is as @JElchison suggested.
